# Generated by Django 5.1.7 on 2025-03-30 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_room_participants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-update', '-created']},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='update',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='updated',
            new_name='update',
        ),
    ]
